import React, { useState } from 'react';
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogFooter 
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Download, FileText, Loader2 } from 'lucide-react';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

interface ShippingLabelGeneratorProps {
  isOpen: boolean;
  onClose: () => void;
  waybill: string;
  shipment?: any; // New prop for local data fallback
  onSuccess?: (message: string) => void;
  onError?: (message: string) => void;
}

type PdfSize = 'A4' | '4R';

export function ShippingLabelGenerator({
  isOpen,
  onClose,
  waybill,
  shipment,
  onSuccess,
  onError
}: ShippingLabelGeneratorProps) {
  const [loading, setLoading] = useState(false);
  const [pdfSize, setPdfSize] = useState<PdfSize>('4R');
  const [outputType, setOutputType] = useState<'pdf' | 'json'>('pdf');
  const [previewData, setPreviewData] = useState<any>(null);
  const [showPreview, setShowPreview] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  // Auto-generate on open
  React.useEffect(() => {
    if (isOpen && !hasAutoGenerated && !loading) {
      setHasAutoGenerated(true);
      handleGenerate();
    }
    if (!isOpen) {
      setHasAutoGenerated(false);
    }
  }, [isOpen]);

  const handleGenerate = async () => {
    try {
      setLoading(true);
      
      const pdf = outputType === 'pdf';
      const response = await fetch(`/api/shipment/label?waybill=${waybill}&pdf=${pdf}&pdf_size=${pdfSize}`);
      
      const contentType = response.headers.get('content-type');
      
      if (contentType && contentType.includes('application/json')) {
        const result = await response.json();
        if (result.isRawData || result.data) {
          // Immediately show the print preview instead of a modal
          handlePrintPreview(result.data);
          onSuccess?.('Label generated and opened for printing.');
          onClose();
          return;
        }
        throw new Error(result.error || 'Failed to generate label');
      }

      // Handle PDF download
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.style.display = 'none';
      a.href = url;
      a.download = `shipping-label-${waybill}-${pdfSize}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      
      onSuccess?.(`Shipping label (${pdfSize}) downloaded successfully`);
      onClose();
    } catch (err: any) {
      console.error('Error generating label:', err);
      onError?.(err.message || 'Failed to generate shipping label');
    } finally {
      setLoading(false);
    }
  };

  const handlePrintPreview = (dataToPrint?: any) => {
    let dataForPrinting = dataToPrint || previewData;
    
    // Aggressive data extraction - look for the package object anywhere in the response
    let data = null;
    if (dataForPrinting) {
      if (Array.isArray(dataForPrinting.packages)) data = dataForPrinting.packages[0];
      else if (dataForPrinting.packages && typeof dataForPrinting.packages === 'object') data = dataForPrinting.packages;
      else if (dataForPrinting.data && Array.isArray(dataForPrinting.data)) data = dataForPrinting.data[0];
      else if (dataForPrinting.data && dataForPrinting.data.packages) data = dataForPrinting.data.packages[0];
      else if (dataForPrinting.data && typeof dataForPrinting.data === 'object' && !dataForPrinting.data.packages) data = dataForPrinting.data;
      else if (Array.isArray(dataForPrinting)) data = dataForPrinting[0];
      else data = dataForPrinting;
    }
    
    // Merge with local shipment data if available
    const localShipment = data?.shipment || dataForPrinting?.shipment || dataForPrinting?.data?.shipment || dataForPrinting?.data?.[0]?.shipment || shipment;
    
    if (localShipment) {
      const isInvalid = (val: any) => !val || val === '--' || val === 'N/A' || val === '000000' || val.toString().trim() === '';
      
      const finalSenderPin = !isInvalid(data?.spin) ? data.spin : (!isInvalid(data?.s_pin) ? data.s_pin : (localShipment.warehouse?.pincode || localShipment.warehouse?.pin || localShipment.packageDetails?.seller_pin || localShipment.packageDetails?.pickup_location?.pin || '000000'));
      const finalSenderPhone = !isInvalid(data?.s_phone) ? data.s_phone : (!isInvalid(data?.sph) ? data.sph : (localShipment.warehouse?.phone || localShipment.seller?.phone || 'N/A'));

      data = {
        ...data,
        oid: data?.oid || localShipment.orderId?._id || localShipment._id,
        snm: !isInvalid(data?.snm) ? data.snm || data.s_name : (localShipment.warehouse?.name || localShipment.packageDetails?.seller_name || 'Sender'),
        sadd: !isInvalid(data?.sadd) ? data.sadd || data.s_addr : (localShipment.warehouse?.address || localShipment.packageDetails?.seller_address || 'Address Not Available'),
        spin: finalSenderPin,
        name: !isInvalid(data?.name) ? data.name : (localShipment.customerDetails?.name || 'Customer'),
        address: !isInvalid(data?.address) ? data.address : (localShipment.customerDetails?.address || 'Address Not Available'),
        pin: !isInvalid(data?.pin) ? data.pin : (localShipment.customerDetails?.pincode || '000000'),
        contact: !isInvalid(data?.contact) ? data.contact : (localShipment.customerDetails?.phone || 'N/A'),
        sph: finalSenderPhone,
        s_phone: finalSenderPhone,
        // Robust product description extraction
        prd: (() => {
          const genericTerms = ['General Product', 'General Items', 'Order Items', 'Store Shipment', 'Standard Shipment', 'Package', 'Items'];
          const delhiveryDesc = data?.prd;
          const enrichedDesc = localShipment.packageDetails?.productDescription;
          
          if (delhiveryDesc && !genericTerms.some(term => delhiveryDesc.toLowerCase().includes(term.toLowerCase()))) {
            return delhiveryDesc;
          }
          
          if (enrichedDesc && !genericTerms.some(term => enrichedDesc.toLowerCase().includes(term.toLowerCase()))) {
            return enrichedDesc;
          }
          
          // Filter items strictly by selectedItemIds if present
          const allItems = localShipment.orderId?.orderItems || localShipment.orderId?.products || [];
          const selectedItems = localShipment.packageDetails?.selectedItemIds && localShipment.packageDetails.selectedItemIds.length > 0
            ? allItems.filter((i: any) => localShipment.packageDetails.selectedItemIds.includes(i._id?.toString() || i.productId?.toString()))
            : allItems;

          if (selectedItems.length > 0) {
            return selectedItems.slice(0, 3).map((i: any) => i.product?.name || i.name).join(', ') + (selectedItems.length > 3 ? '...' : '');
          }
          
          return 'E-Commerce Order Items';
        })(),
        wt: Math.round(Number(data?.wt || localShipment.packageDetails?.weight || '500')),
        // Payment Type Mapping
        pt: (() => {
          const method = (localShipment.orderId?.paymentMethod || localShipment.packageDetails?.paymentMode || 'Pre-paid').toLowerCase();
          return method.includes('cod') ? 'COD' : 'Pre-paid';
        })(),
        // Pricing Logic (with weight-proportional split fallback for MPS)
        cod: (() => {
          const isCOD = (localShipment.orderId?.paymentMethod || localShipment.packageDetails?.paymentMode || '').toLowerCase().includes('cod');
          if (!isCOD) return 0;
          
          let codVal = localShipment.packageDetails?.codAmount; // Don't default to 0 yet
          const orderTotal = localShipment.orderId?.total || localShipment.orderId?.totalAmount || 0;
          
          // Fallback split ONLY if codAmount is truly missing or full total on an MPS shipment
          if (localShipment.shipmentType === 'MPS' || localShipment.packageDetails?.packages) {
            const packages = localShipment.packageDetails?.packages || [];
            if (packages.length > 1 && (codVal === undefined || codVal === null || parseFloat(codVal) === orderTotal)) {
              const totalWeight = packages.reduce((sum: number, p: any) => sum + (p.weight || 500), 0);
              const currentWeight = localShipment.packageDetails?.weight || 500;
              const ratio = currentWeight / Math.max(1, totalWeight);
              codVal = orderTotal * ratio;
            }
          }
          
          // If it's still missing and it's a partial shipment with selected items, calculate from items
          if ((codVal === undefined || codVal === null) && localShipment.packageDetails?.selectedItemIds?.length > 0) {
            const orderItems = localShipment.orderId?.orderItems || localShipment.orderId?.products || [];
            const selectedItems = orderItems.filter((i: any) => 
               localShipment.packageDetails.selectedItemIds.includes(i._id?.toString() || i.productId?.toString()));
            codVal = selectedItems.reduce((sum: number, i: any) => sum + ((i.price || 0) * (i.qty || i.quantity || 1)), 0);
          }
          
          return codVal || orderTotal;
        })(),
        total: (() => {
          let totalVal = localShipment.packageDetails?.totalAmount || 0;
          const orderTotal = localShipment.orderId?.total || localShipment.orderId?.totalAmount || 0;
          
          if ((localShipment.shipmentType === 'MPS' || (localShipment.packageDetails?.packages?.length || 0) > 1) && (!totalVal || totalVal === orderTotal)) {
            const totalWeight = (localShipment.packageDetails?.packages || []).reduce((sum: number, p: any) => sum + (p.weight || 500), 0);
            const currentWeight = localShipment.packageDetails?.weight || 500;
            const ratio = currentWeight / Math.max(1, totalWeight);
            totalVal = orderTotal * ratio;
          }
          
          if (!totalVal && localShipment.packageDetails?.selectedItemIds?.length > 0) {
             const orderItems = localShipment.orderId?.orderItems || localShipment.orderId?.products || [];
             const selectedItems = orderItems.filter((i: any) => 
                localShipment.packageDetails.selectedItemIds.includes(i._id?.toString() || i.productId?.toString()));
             totalVal = selectedItems.reduce((sum: number, i: any) => sum + ((i.price || 0) * (i.qty || i.quantity || 1)), 0);
          }

          return totalVal || orderTotal;
        })()
      };
    }
    
    if (!data) return;

    // Create a new window for printing
    const printWindow = window.open('', '_blank');
    if (printWindow) {
        printWindow.document.write(`
          <!DOCTYPE html>
          <html>
            <head>
              <title>Shipping Label - ${waybill}</title>
              <style>
                body { 
                  font-family: Arial, sans-serif; 
                  margin: 0;
                  padding: 10px;
                  background: white;
                }
                .label-container {
                  width: ${pdfSize === 'A4' ? '7.5in' : '3.8in'};
                  border: 2px solid #000;
                  padding: 5px;
                  margin: 0 auto;
                  position: relative;
                }
                .label-header {
                  display: flex;
                  justify-content: space-between;
                  align-items: center;
                  border-bottom: 2px solid #000;
                  padding: 5px;
                }
                .logo-img { height: 30px; }
                .label-title { font-weight: bold; font-size: 14px; }
                
                .barcode-section {
                  text-align: center;
                  padding: 10px;
                  border-bottom: 2px solid #000;
                }
                .barcode-img { width: 90%; max-height: 80px; }
                
                .grid-2 {
                  display: grid;
                  grid-template-columns: 1fr 1fr;
                  border-bottom: 1px solid #000;
                }
                .cell {
                  padding: 5px;
                  border-right: 1px solid #000;
                  font-size: 11px;
                }
                .cell:last-child { border-right: none; }
                
                .label-info {
                  padding: 5px;
                  font-size: 11px;
                  border-bottom: 1px solid #000;
                }
                .label-info.no-border { border-bottom: none; }
                
                .bold { font-weight: bold; }
                .uppercase { text-transform: uppercase; }
                .waybill { font-size: 14px; margin-top: 5px; }
                
                .address-section {
                  display: grid;
                  grid-template-columns: 1fr 1fr;
                  gap: 10px;
                  padding: 5px;
                  font-size: 11px;
                }
                .ship-to { background: #000; color: #fff; padding: 2px 5px; font-weight: bold; margin-bottom: 5px; }

                @media print {
                  .no-print { display: none; }
                  body { padding: 0; }
                  .label-container { border: 2px solid #000; }
                }
              </style>
            </head>
            <body>
              <div class="label-container" id="label">
                <div class="label-header">
                  <div class="label-title">E-COMMERCE LABEL</div>
                  <img src="${data.delhivery_logo || 'https://track.delhivery.com/static/images/new_logo.png'}" class="logo-img" alt="Delhivery" />
                </div>
                
                <div class="barcode-section">
                  <img src="${data.barcode || `https://bwipjs-api.metafloor.com/?bcid=code128&text=${data.wbn || waybill}&scale=3&rotate=N&includetext`}" class="barcode-img" alt="Barcode" />
                  <div class="waybill bold uppercase">WAYBILL: ${data.wbn || waybill}</div>
                </div>
                
                <div class="grid-2">
                  <div class="cell" style="word-break: break-all;">
                    <div class="bold text-xs">ORDER ID:</div>
                    <div style="font-size: 9px;">${data.oid || data.order_id || data.client_order_id || 'N/A'}</div>
                  </div>
                  <div class="cell">
                    <div class="bold text-xs">DATE:</div>
                    <div>${new Date(data.cd || new Date()).toLocaleDateString()}</div>
                  </div>
                </div>

                <div class="address-section">
                  <div class="ship-from">
                    <div class="bold uppercase" style="border-bottom: 1px solid #000; margin-bottom: 4px;">SHIP FROM:</div>
                    <div class="bold">${data.snm || data.s_name || data.sender_name || 'Sender'}</div>
                    <div style="font-size: 10px;">${data.sadd || data.s_addr || data.sender_address || 'Address Not Available'}</div>
                    <div class="bold">PIN: <span id="s-pin-display">${data.spin || data.s_pin || data.sender_pin || '--'}</span></div>
                    <div class="bold">PH: <span id="s-ph-display">${data.s_phone || data.s_contact || data.sph || '--'}</span></div>
                  </div>
                  <div class="ship-to-content">
                    <div class="ship-to uppercase">SHIP TO:</div>
                    <div class="bold uppercase">${data.name || data.customer_name || data.consignee_name || 'Customer'}</div>
                    <div style="font-size: 10px;">${data.address || data.dest_add || data.shipping_address || 'Address Not Available'}</div>
                    <div class="bold uppercase">PIN: ${data.pin || data.pincode || data.dest_pin || '000000'}</div>
                    <div class="bold">PH: ${data.contact || data.phone || data.mobile || data.c_phone || 'N/A'}</div>
                  </div>
                </div>

                <div class="label-info">
                  <div class="bold underline uppercase">PRODUCT DESCRIPTION:</div>
                  <div id="description-display" style="font-size: 10px; min-height: 20px;">${data.prd || data.product_desc || data.description || 'General Product'}</div>
                  ${(data.l || data.length || data.w || data.width || data.h || data.height) ? `
                    <div style="font-size: 10px; margin-top: 4px; border-top: 1px dashed #ccc; padding-top: 2px;">
                      DIM: ${data.l || data.length || data.shipment_length || '?'} x ${data.w || data.width || data.shipment_width || '?'} x ${data.h || data.height || data.shipment_height || '?'} cm
                    </div>
                  ` : ''}
                </div>

                <div class="grid-2" style="border-bottom: none;">
                  <div class="cell">
                    <div class="bold uppercase">METHOD: <span id="method-display">${data.pt === 'Pre-paid' || data.pt === 'Prepaid' || data.payment_mode === 'Prepaid' ? 'PREPAID' : (data.pt === 'COD' ? 'C.O.D' : data.pt || 'PREPAID')}</span></div>
                    <div class="bold" style="font-size: 16px; margin-top: 5px;">
                      <span id="price-label">
                        ${(data.pt === 'COD' || data.payment_mode === 'COD') ? 'COLLECT: ' : 'PAID: '}
                      </span>
                      ₹<span id="price-display">${Math.round(Number((data.pt === 'COD' || data.payment_mode === 'COD') ? (data.cod || 0) : (data.total || shipment?.orderId?.total || 0)))}</span>
                    </div>
                  </div>
                  <div class="cell" style="text-align: right;">
                    <div class="bold uppercase" id="weight-display">WEIGHT: ${data.wt || '500'} ${data.weight_unit || 'G'}</div>
                    <div class="bold uppercase" id="qty-display">QTY: ${data.qty || shipment?.orderId?.orderItems?.length || shipment?.orderId?.products?.length || '1'}</div>
                  </div>
                </div>

                <div class="no-print" style="margin-top: 20px; padding: 20px; border: 2px dashed #000; background: #fdfdfd; border-radius: 8px;">
                  <h3 style="margin-top: 0; color: #000; border-bottom: 2px solid #000; padding-bottom: 5px; margin-bottom: 15px;">MANUAL LABEL ADJUSTMENTS</h3>
                  
                  <!-- SENDER INFO (MOST IMPORTANT) -->
                  <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 15px; text-align: left; background: #fff; padding: 10px; border: 1px solid #ddd; border-radius: 4px;">
                    <div>
                      <label style="display: block; font-weight: bold; margin-bottom: 5px; color: #000;">Sender PIN:</label>
                      <input 
                        id="s-pin-override" 
                        value="${data.spin || '000000'}"
                        style="width: 100%; padding: 10px; font-size: 16px; border: 2px solid #000; border-radius: 4px; box-sizing: border-box;"
                        oninput="document.getElementById('s-pin-display').innerText = this.value"
                      />
                    </div>
                    <div>
                      <label style="display: block; font-weight: bold; margin-bottom: 5px; color: #000;">Sender Phone:</label>
                      <input 
                        id="s-ph-override" 
                        value="${data.s_phone || data.sph || 'N/A'}"
                        style="width: 100%; padding: 10px; font-size: 16px; border: 2px solid #000; border-radius: 4px; box-sizing: border-box;"
                        oninput="document.getElementById('s-ph-display').innerText = this.value"
                      />
                    </div>
                  </div>

                  <!-- PRICE AND WEIGHT -->
                  <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 15px; text-align: left;">
                    <div>
                      <label style="display: block; font-weight: bold; margin-bottom: 5px; color: #333;">Collect Price (₹):</label>
                      <input 
                        type="number" 
                        id="price-override" 
                        value="${Math.round(Number((data.pt === 'COD' || data.payment_mode === 'COD') ? (data.cod || 0) : (data.total || shipment?.orderId?.total || 0)))}"
                        style="width: 100%; padding: 10px; font-size: 16px; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box;"
                        oninput="document.getElementById('price-display').innerText = Math.round(parseFloat(this.value || 0))"
                      />
                    </div>
                    <div>
                      <label style="display: block; font-weight: bold; margin-bottom: 5px; color: #333;">Package Weight (G):</label>
                      <input 
                        type="number" 
                        value="${data.wt || '500'}"
                        style="width: 100%; padding: 10px; font-size: 16px; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box;"
                        oninput="document.getElementById('weight-display').innerText = 'WEIGHT: ' + this.value + ' G'"
                      />
                    </div>
                  </div>

                  <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 15px; text-align: left;">
                    <div>
                      <label style="display: block; font-weight: bold; margin-bottom: 5px; color: #333;">Quantity (QTY):</label>
                      <input 
                        type="number" 
                        value="${data.qty || shipment?.orderId?.orderItems?.length || 1}"
                        style="width: 100%; padding: 10px; font-size: 16px; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box;"
                        oninput="document.getElementById('qty-display').innerText = 'QTY: ' + this.value"
                      />
                    </div>
                    <div>
                      <!-- Placeholder for spacing -->
                    </div>
                  </div>

                  <div style="margin-bottom: 15px; text-align: left;">
                    <label style="display: block; font-weight: bold; margin-bottom: 5px; color: #333;">Product Description:</label>
                    <textarea 
                      id="description-override" 
                      style="width: 100%; padding: 10px; font-size: 14px; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; min-height: 60px;"
                      oninput="document.getElementById('description-display').innerText = this.value"
                    >${data.prd || data.product_desc || data.description || 'General Product'}</textarea>
                  </div>
                  
                  <div style="display: flex; gap: 10px; justify-content: center;">
                    <button onclick="window.print()" style="flex: 2; padding: 12px 20px; font-size: 16px; background: #000; color: white; border: none; border-radius: 4px; cursor: pointer; font-weight: bold;">PRINT LABEL</button>
                    <button onclick="window.close()" style="flex: 1; padding: 12px 20px; font-size: 16px; background: #fff; color: #000; border: 1px solid #000; border-radius: 4px; cursor: pointer;">CLOSE</button>
                  </div>
                </div>
                
                <script>
                  // Auto-focus the price override input
                  window.onload = function() {
                    const input = document.getElementById('price-override');
                    if (input) input.select();
                    console.log('Label Ready');
                  };
                </script>
              </div>
            </body>
          </html>
        `);
        printWindow.document.close();
    }
  };

  return (
    <>
      <Dialog open={isOpen} onOpenChange={onClose}>
        <DialogContent className="sm:max-w-[600px]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5" />
              Generate Shipping Label
            </DialogTitle>
          </DialogHeader>
          
          <div className="space-y-6">
            <div className="text-sm text-gray-600">
              Waybill: <span className="font-mono font-semibold">{waybill}</span>
            </div>

            {/* PDF Size Selection */}
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Label Size</CardTitle>
                <CardDescription>
                  Choose the size for your shipping label
                </CardDescription>
              </CardHeader>
              <CardContent>
                <RadioGroup
                  value={pdfSize}
                  onValueChange={(value: PdfSize) => setPdfSize(value)}
                  className="grid grid-cols-2 gap-4"
                >
                  <div className="flex items-center space-x-2 border rounded-lg p-4">
                    <RadioGroupItem value="4R" id="4R" />
                    <Label htmlFor="4R" className="cursor-pointer flex-1">
                      <div className="font-semibold">4R Size (4×6 inches)</div>
                      <div className="text-sm text-gray-600">
                        Standard shipping label size
                      </div>
                    </Label>
                  </div>
                  <div className="flex items-center space-x-2 border rounded-lg p-4">
                    <RadioGroupItem value="A4" id="A4" />
                    <Label htmlFor="A4" className="cursor-pointer flex-1">
                      <div className="font-semibold">A4 Size (8.27×11.69 inches)</div>
                      <div className="text-sm text-gray-600">
                        Full page format
                      </div>
                    </Label>
                  </div>
                </RadioGroup>
              </CardContent>
            </Card>

            {/* Output Type Selection */}
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Output Format</CardTitle>
                <CardDescription>
                  Choose how you want to receive the label
                </CardDescription>
              </CardHeader>
              <CardContent>
                <RadioGroup
                  value={outputType}
                  onValueChange={(value: 'pdf' | 'json') => setOutputType(value)}
                  className="space-y-3"
                >
                  <div className="flex items-center space-x-2">
                    <RadioGroupItem value="pdf" id="pdf" />
                    <Label htmlFor="pdf" className="cursor-pointer">
                      <div className="font-semibold">PDF Download</div>
                      <div className="text-sm text-gray-600">
                        Ready-to-print PDF file (recommended)
                      </div>
                    </Label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <RadioGroupItem value="json" id="json" />
                    <Label htmlFor="json" className="cursor-pointer">
                      <div className="font-semibold">Custom Preview</div>
                      <div className="text-sm text-gray-600">
                        Preview and customize label layout
                      </div>
                    </Label>
                  </div>
                </RadioGroup>
              </CardContent>
            </Card>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={onClose} disabled={loading}>
              Cancel
            </Button>
            <Button onClick={handleGenerate} disabled={loading}>
              {loading ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Download className="h-4 w-4 mr-2" />
                  Generate Label
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Preview Dialog */}
      <Dialog open={showPreview} onOpenChange={setShowPreview}>
        <DialogContent className="sm:max-w-[800px] max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Label Preview</DialogTitle>
          </DialogHeader>
          
          {previewData && (
            <div className="space-y-4">
              <div className="bg-gray-50 p-4 rounded-lg">
                <h3 className="font-semibold mb-2">Label Data:</h3>
                <pre className="text-sm overflow-x-auto whitespace-pre-wrap">
                  {JSON.stringify(previewData, null, 2)}
                </pre>
              </div>
              
              <div className="flex gap-2">
                <Button onClick={handlePrintPreview} className="flex-1">
                  <FileText className="h-4 w-4 mr-2" />
                  Print Label (Browser PDF)
                </Button>
                <Button 
                  variant="outline" 
                  onClick={() => {
                    handlePrintPreview();
                  }}
                >
                  <Download className="h-4 w-4 mr-2" />
                  Save as PDF
                </Button>
              </div>
            </div>
          )}
          
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowPreview(false)}>
              Close
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
